// <auto-generated />
using System;
using Labb__Minimal_API___Anrop_till_ASP.Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb__Minimal_API___Anrop_till_ASP.Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb__Minimal_API___Anrop_till_ASP.Net.Models.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("2ab5a7ae-3d9b-4d20-810e-f6251df1d5e5"),
                            Author = "J.K. Rowling",
                            Description = "Book about Harry Potter and his wizarding friends.",
                            Genre = "Fantasy",
                            IsAvailable = true,
                            PublicationYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            ID = new Guid("cde12fa6-53c7-405f-8a09-c30b79d1b95e"),
                            Author = "Suzanne Collins",
                            Description = "We follow Katniss Everdeen and her struggles.",
                            Genre = "Science fiction",
                            IsAvailable = false,
                            PublicationYear = 2008,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            ID = new Guid("bea4ed64-1dcb-4e02-8c6f-6c4fc24ad59b"),
                            Author = "Jordan Belfort",
                            Description = "About Jordan Belforts interesting life!",
                            Genre = "Autobiography",
                            IsAvailable = true,
                            PublicationYear = 2008,
                            Title = "Wolf of the Wall Street"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
