// <auto-generated />
using Labb__Minimal_API___Anrop_till_ASP.Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb__Minimal_API___Anrop_till_ASP.Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb__Minimal_API___Anrop_till_ASP.Net.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "J.K. Rowling",
                            Description = "Book about Harry Potter and his wizarding friends.",
                            Genre = "Fantasy",
                            IsAvailable = true,
                            PublicationYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Suzanne Collins",
                            Description = "We follow Katniss Everdeen and her struggles.",
                            Genre = "Science fiction",
                            IsAvailable = false,
                            PublicationYear = 2008,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Jordan Belfort",
                            Description = "About Jordan Belforts interesting life!",
                            Genre = "Autobiography",
                            IsAvailable = true,
                            PublicationYear = 2008,
                            Title = "Wolf of the Wall Street"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
